export const LIST_BREED = {
    Dog:[
        'Labrador Retriever',
        'Golden Retriever',
        'German Shepherd',
        'French Bulldog',
        'Bulldog',
        'Poodle',
        'Beagle',
        'Yorkshire Terrier',
        'Dachshund',
        'Boxer',
        'Siberian Husky',
        'Cavalier King Charles Spaniel',
        'Shih Tzu',
        'Great Dane',
        'Chihuahua',
        'Pomeranian',
        'Australian Shepherd',
        'Border Collie',
        'Shetland Sheepdog',
        'Rottweiler'
    ],
    Cat: [
        'American Shorthair',
        'Siamese',
        'Maine Coon',
        'Persian',
        'British Shorthair',
        'Ragdoll',
        'Bengal',
        'Sphynx',
        'Russian Blue',
        'Scottish Fold',
        'Norwegian Forest Cat',
        'Burmese',
        'Devon Rex',
        'Siberian',
        'Oriental',
        'Abyssinian',
        'Cornish Rex',
        'Himalayan',
        'Tonkinese',
        'Manx'
    ],
    Bird:[
        'Budgerigar (Budgie)',
        'Cockatiel',
        'Lovebird',
        'African Grey Parrot',
        'Canary',
        'Finch',
        'Cockatoo',
        'Macaw',
        'Conure',
        'Amazon Parrot',
        'Parakeet',
        'Eclectus Parrot',
        'Quaker Parrot',
        'Caique',
        'Pionus Parrot',
        'Lorikeet',
        'Senegal Parrot',
        'Poicephalus Parrot',
        'Rosella',
        'Cockatiel'
    ],
    Other: [
        'Other'
    ]
}

export const URL = "http://localhost:8080"