server:
  port: 8080
  servlet:
    session:
      timeout: -1
      cookie:
        name: JSESSIONID

spring:
  datasource:
    password: 12345678
    url: "jdbc:mysql://localhost:3306/pethealthcarev2"
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true