server:
  port: 8080
  servlet:
    session:
      timeout: -1
      cookie:
        name: JSESSIONID

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pethealthcare"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: "dathtvse170567@fpt.edu.vn"
    password: "aran vhqy rblp xvka"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB