server:
  port: 8080
  servlet:
    session:
      timeout: -1
      cookie:
        name: JSESSIONID

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pethealthcarev2"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "dathtvse170567@fpt.edu.vn"
    password: "aran vhqy rblp xvka"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
